import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Linking,
  Alert,
} from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";

export default function ScanScreen() {
  const [permission, requestPermission] = useCameraPermissions();
  const [scannedPhone, setScannedPhone] = useState(null);
  const [scanned, setScanned] = useState(false);

  useEffect(() => {
    if (permission && !permission.granted) {
      requestPermission();
    }
  }, [permission]);

  const handleBarcodeScanned = ({ data }) => {
    if (scanned) return;
    setScanned(true);

    // QR codes generated by Pallavi encode "tel:+91XXXXXXXXXX"
    let phone = data;
    if (data.startsWith("tel:")) {
      phone = data.replace("tel:", "");
    }
    setScannedPhone(phone);
  };

  const scanAgain = () => {
    setScanned(false);
    setScannedPhone(null);
  };

  const callNumber = () => {
    if (!scannedPhone) return;
    Linking.openURL(`tel:${scannedPhone}`).catch(() =>
      Alert.alert("Unable to dial", "This device can't place calls.")
    );
  };

  if (!permission) {
    return <View style={styles.center} />;
  }

  if (!permission.granted) {
    return (
      <View style={styles.center}>
        <Text style={styles.permText}>Camera access is needed to scan QR codes.</Text>
        <TouchableOpacity style={styles.button} onPress={requestPermission}>
          <Text style={styles.buttonText}>Grant Permission</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (scannedPhone) {
    return (
      <View style={styles.center}>
        <Text style={styles.label}>Scanned Number</Text>
        <Text style={styles.phoneText}>{scannedPhone}</Text>

        <TouchableOpacity style={styles.callButton} onPress={callNumber}>
          <Text style={styles.buttonText}>📞 Call Now</Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.secondaryButton} onPress={scanAgain}>
          <Text style={styles.secondaryButtonText}>Scan Another Code</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <CameraView
        style={StyleSheet.absoluteFillObject}
        barcodeScannerSettings={{ barcodeTypes: ["qr"] }}
        onBarcodeScanned={handleBarcodeScanned}
      />
      <View style={styles.overlay}>
        <View style={styles.frame} />
        <Text style={styles.overlayText}>Point the camera at a Pallavi QR code</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#fff", padding: 24 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  frame: {
    width: 240,
    height: 240,
    borderWidth: 3,
    borderColor: "#fff",
    borderRadius: 16,
  },
  overlayText: { color: "#fff", marginTop: 20, fontSize: 14, backgroundColor: "rgba(0,0,0,0.4)", padding: 8, borderRadius: 8 },
  permText: { fontSize: 15, color: "#444", textAlign: "center", marginBottom: 16 },
  label: { color: "#888", fontSize: 13, marginBottom: 6 },
  phoneText: { fontSize: 26, fontWeight: "800", color: "#222", marginBottom: 28 },
  button: { backgroundColor: "#5B2A86", paddingVertical: 12, paddingHorizontal: 24, borderRadius: 10 },
  callButton: { backgroundColor: "#2e9e4f", paddingVertical: 16, paddingHorizontal: 40, borderRadius: 12, marginBottom: 14 },
  secondaryButton: { paddingVertical: 10, paddingHorizontal: 20 },
  secondaryButtonText: { color: "#5B2A86", fontWeight: "600" },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
});
